-- local function clear_harpoon_on_exit()
--     local ok, harpoon = pcall(require, "harpoon.mark")
--     if not ok then
--         print("Harpoon not installed")
--         return
--     end
--     harpoon.clear_all()
-- end
--
-- vim.api.nvim_create_autocmd("VimLeavePre", {
--     callback = clear_harpoon_on_exit,
--     desc = "Clear all Harpoon files on Neovim exit",
-- })
--
